FROM node:20.8.0-alpine3.17

RUN addgroup app && adduser -S -G app app

USER app

WORKDIR /app

COPY --chown=app:node package*.json All.crt ./

RUN npm config set strict-ssl=false \
    && npm config set cafile="./All.crt" \
    && npm  install

COPY --chown=app:node . .

EXPOSE $VITE_PORT

HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
    CMD npm run healthcheck

CMD ["npm", "run", "dev"]

